# Generated by Django 5.2.5 on 2025-08-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_devicepreview_writingtheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
