# Generated by Django 5.2.4 on 2025-08-21 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0009_remove_document_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users with whom this document is shared', related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
