# Generated by Django 5.2.4 on 2025-08-28 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0012_creativenotebook_creativenode_nodeconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('ethereal', 'Ethereal (Default)'), ('forest', 'Forest Green'), ('ocean', 'Ocean Blue'), ('sunset', 'Sunset Orange'), ('midnight', 'Midnight Dark'), ('lavender', 'Lavender Purple'), ('autumn', 'Autumn Warm'), ('monochrome', 'Monochrome')], default='ethereal', max_length=20)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('x-large', 'Extra Large')], default='medium', max_length=10)),
                ('writing_goal_daily', models.IntegerField(default=500, help_text='Daily word count goal')),
                ('preferred_editor', models.CharField(choices=[('ultimate', 'Ultimate Editor'), ('simple', 'Simple Editor'), ('academic', 'Academic Editor'), ('google_docs', 'Google Docs Style')], default='ultimate', max_length=20)),
                ('show_statistics', models.BooleanField(default=True)),
                ('show_bookshelf', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
