# Generated by Django 5.2.5 on 2025-08-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0008_document_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='shared_with',
        ),
    ]
