# Generated by Django 5.2.4 on 2025-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0010_document_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_assistance_level',
            field=models.CharField(choices=[('minimal', 'Minimal AI Help'), ('medium', 'Standard AI Assistance'), ('maximum', 'Maximum AI Integration')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_dashboard',
            field=models.BooleanField(default=True, help_text='Show this project on the dashboard bookshelf'),
        ),
        migrations.AddField(
            model_name='project',
            name='writing_style_guide',
            field=models.CharField(choices=[('mla', 'MLA Format'), ('apa', 'APA Format'), ('chicago', 'Chicago Style'), ('custom', 'Custom Style')], default='mla', max_length=20),
        ),
    ]
