# Generated by Django 5.2.5 on 2025-08-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0013_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('character_development', 'Character Development'), ('plot_brainstorming', 'Plot Brainstorming'), ('world_building', 'World Building'), ('general_creative', 'General Creative Session'), ('problem_solving', 'Problem Solving')], default='general_creative', max_length=30)),
                ('character_ideas', models.JSONField(blank=True, default=list, help_text='Character ideas generated in this session')),
                ('plot_ideas', models.JSONField(blank=True, default=list, help_text='Plot ideas generated in this session')),
                ('world_building_notes', models.JSONField(blank=True, default=list, help_text='World building concepts')),
                ('general_notes', models.TextField(blank=True, help_text='General notes from the session', null=True)),
                ('ai_suggestions_used', models.JSONField(blank=True, default=list, help_text='AI suggestions that were accepted/used')),
                ('connections_made', models.JSONField(blank=True, default=list, help_text='Idea connections made during session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_duration_minutes', models.IntegerField(default=0, help_text='How long the session lasted')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the user marked the session as complete')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived sessions are hidden from main view')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_sessions', to='writer.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
