# Generated by Django 5.2.4 on 2025-09-02 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0014_workshopsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media_library/')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=10)),
                ('file_format', models.CharField(blank=True, max_length=10, null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('duration', models.DurationField(blank=True, help_text='Duration for video/audio files', null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Width/height for images/videos', null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text content from documents', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional file metadata')),
                ('tags', models.JSONField(default=list, help_text='User-defined tags')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='writer.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
