# Generated by Django 5.2.5 on 2025-09-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0015_mediafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_save_enabled', models.BooleanField(default=True, help_text='Automatically create versions on save')),
                ('auto_save_interval', models.IntegerField(default=10, help_text='Minutes between auto-saves')),
                ('max_versions_to_keep', models.IntegerField(default=50, help_text='Maximum versions to keep per document')),
                ('notify_on_version_save', models.BooleanField(default=True, help_text='Show notifications when versions are saved')),
                ('require_save_reason', models.BooleanField(default=False, help_text='Require reason when manually saving versions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='version_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('save_reason', models.CharField(blank=True, help_text='Reason for saving this version', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_count', models.IntegerField(default=0)),
                ('is_major_version', models.BooleanField(default=False, help_text='Mark important versions')),
                ('is_published_version', models.BooleanField(default=False, help_text='Version that was published')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='writer.chapter')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_versions_saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('chapter', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('save_reason', models.CharField(blank=True, help_text='Reason for saving this version', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_count', models.IntegerField(default=0)),
                ('is_major_version', models.BooleanField(default=False, help_text='Mark important versions')),
                ('is_published_version', models.BooleanField(default=False, help_text='Version that was published')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='writer.document')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions_saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
