# Generated by Django 5.2.5 on 2025-09-02 18:20

from django.db import migrations
from django.db import connection


def fix_document_version_table(apps, schema_editor):
    """Fix the DocumentVersion table structure"""
    cursor = connection.cursor()
    
    # Drop the existing table and recreate it with correct structure
    cursor.execute("DROP TABLE IF EXISTS writer_documentversion;")
    
    cursor.execute("""
        CREATE TABLE writer_documentversion (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            version_number INTEGER NOT NULL,
            title VARCHAR(200) NOT NULL,
            content TEXT NOT NULL,
            save_reason VARCHAR(100),
            created_at DATETIME NOT NULL,
            word_count INTEGER DEFAULT 0,
            is_major_version BOOLEAN DEFAULT 0,
            is_published_version BOOLEAN DEFAULT 0,
            document_id INTEGER NOT NULL REFERENCES writer_document(id) ON DELETE CASCADE,
            saved_by_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
            UNIQUE(document_id, version_number)
        );
    """)
    
    # Create indexes
    cursor.execute("CREATE INDEX writer_documentversion_document_id_idx ON writer_documentversion(document_id);")
    cursor.execute("CREATE INDEX writer_documentversion_saved_by_id_idx ON writer_documentversion(saved_by_id);")


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0017_auto_20250902_1416'),
    ]

    operations = [
        migrations.RunPython(fix_document_version_table),
    ]
