# Generated by Django 5.2.5 on 2025-09-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0018_auto_20250902_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_quotes',
            field=models.TextField(blank=True, help_text='Quotes that motivate your writing', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_writers',
            field=models.TextField(blank=True, help_text='Authors who inspire you', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hopes_and_dreams',
            field=models.TextField(blank=True, help_text='Your writing goals and aspirations', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Your writing interests (e.g., fantasy, sci-fi, romance, mystery)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text="Where you're writing from", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal website or blog', null=True),
        ),
    ]
