# Generated by Django 5.2.5 on 2025-08-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0005_add_google_docs_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevicePreview',
        ),
    ]
