# Generated by Django 5.2.5 on 2025-08-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0006_delete_devicepreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
